### PR TITLE
Fixed PHP7 port. Restored commented reference counting.

### PR DESCRIPTION
**Pull request by Jan-E**
Updated version of https://github.com/php/pecl-networking-ssh2/pull/30
Changed GC_REFCOUNT(p)++ into GC_ADDREF(p) for PHP 7.3 as well

### CODE REVIEW

**Comment by Jan-E** [comment]
@remicollet Please review and merge

**Comment by remicollet** [comment]
Still an annoying build warning
```
/home/php/git/ssh2/ssh2_fopen_wrappers.c: In function 'php_ssh2_fopen_wraper_parse_path':
/home/php/git/ssh2/ssh2_fopen_wrappers.c:460:2: warning: 'zsession.value.res' may be used uninitialized in this function [-Wmaybe-uninitialized]
  zend_list_delete(Z_RES(zsession));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/php/Zend/zend.h:31:0,
                 from /usr/include/php/main/php.h:35,
                 from /home/php/git/ssh2/ssh2_fopen_wrappers.c:25:
/usr/include/php/Zend/zend_types.h:558:37: warning: 'zsftp.value.res' may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define Z_RES(zval)     (zval).value.res
 
```                                    ^

**Comment by remicollet** [comment]
Forget previous... test suite ok.

**Comment by remicollet** [comment]
```
=====================================================================
PHP         : /opt/remi/php73/root/usr/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.3.0alpha2
ZEND_VERSION: 3.3.0-dev
PHP_OS      : Linux - Linux builder.remirepo.net 4.16.16-200.fc27.x86_64 #1 SMP Sun Jun 17 03:06:00 UTC 2018 x86_64
INI actual  : /home/php/git/ssh2
More .INIs  :   
CWD         : /home/php/git/ssh2
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2018-06-28 07:38:20
=====================================================================
PASS ssh2_auth_FOO() - Attempt to authenticate to a remote host [tests/ssh2_auth.phpt] 
PASS ssh2_auth_pubkey_file() - Tests authentication with a key [tests/ssh2_auth_key.phpt] 
PASS ssh2_connect() Basic connection and pre-authentication [tests/ssh2_connect.phpt] 
PASS ssh2_shell_test() - Tests opening a shell [tests/ssh2_exec.phpt] 
PASS ssh2_sftp - SFTP tests [tests/ssh2_sftp_001.phpt] 
PASS ssh2_sftp - SFTP tests [tests/ssh2_sftp_002.phpt] 
PASS ssh2_shell_test() - Tests opening a shell [tests/ssh2_shell.phpt] 
=====================================================================
TIME END 2018-06-28 07:38:23

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   16
---------------------------------------------------------------------

Number of tests :    7                 7
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    7 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :    3 seconds
=====================================================================

```

**Comment by remicollet** [comment]
Merged
Thanks

@langemeijer as this is your extension, please check, and perhaps worth an 1.1.3 bugfix release ?

**Comment by Jan-E** [comment]
> @langemeijer as this is your extension, please check, and perhaps worth an 1.1.3 bugfix release ?

Any chance for a new release on PECL? People are asking for it:
https://github.com/iuscommunity/wishlist/issues/175#issuecomment-407172286

**Comment by remicollet** [comment]
@Jan-E RPM users should use my repo (working with upstream)  instead of IUS (waiting for upstream)  ;)

**Comment by virgofx** [comment]
@remicollet Thinking about switching; however, it still shows 1.1.2 ?

https://rpms.remirepo.net/enterprise/7/php72/x86_64/repoview/php-pecl-ssh2.html

Need the latest which has proper PHP 7.x support

**Comment by langemeijer** [comment]
I will be preparing a new release in a few weeks.

**Comment by remicollet** [comment]
> @remicollet Thinking about switching; however, it still shows 1.1.2 ?

@virgofx it is 1.1.2 + needed patches

**Comment by virgofx** [comment]
Sorry having a hard time understanding... for clarification

php-pecl-ssh2-1.1.2-2.el7.remi.7.2.x86_64  --- Should work with PHP7.2?

And once PECL releases 1.1.3, Remi repo will bump the version as well to latest?

**Comment by remicollet** [comment]
> php-pecl-ssh2-1.1.2-2.el7.remi.7.2.x86_64 --- Should work with PHP7.2?

Yes

> And once PECL releases 1.1.3, Remi repo will bump the version as well to latest?

Yes

**Pull request closed without merging**
