### PR TITLE
ssh2: IS_CALLABLE_CHECK_SILENT

### PR DESCRIPTION
**Pull request by kornrunner**
Update check for PHP8

### CODE REVIEW

**Comment by langemeijer** [comment]
Ah yes.. I noticed this too. It stopped compilation for 8.0 because IS_CALLABLE_CHECK_NO_ACCESS has been removed.

Can you give your rationale on why it should be IS_CALLABLE_CHECK_SILENT? I reverted it back to the `0` value that is had before.

**Comment by pauci** [comment]
Should the new release 1.3 actually work with PHP >= 8.0? I'm getting failed dependency constraint:
```
pecl/ssh2 requires PHP (version >= 7.0.0, version <= 8.0.0), installed version is 8.0.2
```

**Comment by remicollet** [comment]
package.xml is wrong, as it keep maximal allowed version to 8.0.0

**Comment by langemeijer** [comment]
Will fix now. package.xml in the tarball indeed is wrong

**Comment by kornrunner** [comment]
Thank you!

**Pull request closed without merging**
